language: node_js
node_js:
  - "6"
branches:
  only: master
script:
  - npm run build
after_script:
  - git init
  - git config user.name "Dafrok"
  - git config user.email "o.o@mug.dog"
  - git add .
  - git commit -m "Travis build prepare"
  - git push "https://${GITHUB_TOKEN}@github.com/Dafrok/css-color-playground.git" master:gh-pages --force --quiet
